/**********************************************************************/
/*id fields are created here that will automatically increment as well*/ 
/*as updated_at and created_at fields using the t.timestamps method.  */
/**********************************************************************/

    exports.up = function (knex) {
    
        return knex.schema.createTable('client', function (t) {
            t.increments('id').primary()
            t.string('firstname').notNullable()
            t.string('surname').notNullable()
            t.string('address').notNullable()
            t.string('postcode').notNullable()
            t.string('telephone').notNullable()
            t.string('mobilePhone').notNullable()
            t.string('email').notNullable()
            t.string('ocpMum').nullable()
            t.string('ocpDad').nullable()
            t.string('nationality').nullable()
            t.string('religion').notNullable()
            t.string('language').nullable()
            t.string('marStatus').nullable()
            t.string('haveChild').notNullable()
            t.string('noOfChild').notNullable()
            t.string('childrenName').notNullable()
            t.string('childAttend').notNullable()
            t.string('schDist').nullable()
            t.string('homeStay').notNullable()
            t.string('specialNeeds').notNullable()
            t.string('chilInfo').notNullable()
            t.string('expectMother').nullable()
            t.string('familyInfo').nullable()
            t.string('pet').nullable()
            t.string('specPet').nullable()
            t.string('familyHobby').nullable()
            t.string('smokeStatus').nullable()
            t.string('safeIssues').notNullable()
            t.string('info').nullable()
            t.string('accoType').nullable()
            t.string('specificHouseType').nullable()
            t.string('recepRoom').nullable()
            t.string('noOfBedroom').nullable()
            t.string('noOfBathroom').nullable()
            t.string('noOfFloor').nullable()
            t.string('nearestStation').nullable()
            t.string('aupairHaveRoom').notNullable()
            t.string('describeAccomodation').notNullable()
            t.string('facilities').nullable()
            t.string('typeRequired').nullable()
            t.string('lengthOfService').notNullable()
            t.string('agePreffered').nullable()
            t.string('prefferedNationality').nullable()
            t.string('prefferedGender').nullable()
            t.string('reqExperience').nullable()
            t.string('resp').nullable()
            t.string('license').nullable()
            t.string('levelOfEnglish').nullable()
            t.string('languageWanted').nullable()
            t.string('will you do phone interviews?').notNullable()
            t.string('totalWorkingHours').notNullable()
            t.string('duties').notNullable()
            t.string('daysOfWork').notNullable()
            t.string('timeToCommence').notNullable()
            t.timestamps(false, true)
        })
    }
    exports.down = function (knex) {
        return knex.schema.dropTableIfExists('client')
    }
